//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//
//  Template generated by Sawan Kumar
//

import UIKit

class ___VARIABLE_productName:identifier___View: UIView {

	weak var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?

    override init(frame: CGRect) {
        super.init(frame: frame)
        setupUI()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
    }

    private func setupUI() {
        
    }
    
    func updateUI(with data:___VARIABLE_productName:identifier___ModelProtocol) {
        
    }
}
