//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//
//  Template generated by Sawan Kumar
//

import Foundation


//MARK: View State -
enum ___VARIABLE_productName:identifier___ViewState {
    case initial
    case startLoader
    case stopLoader
    case empty
    case error(NSError)
    case populate(___VARIABLE_productName:identifier___ModelProtocol)
}

//MARK: Presenter Input State -
enum ___VARIABLE_productName:identifier___PresenterState {
    case fetch
}

//MARK: Interactor Output State -
enum ___VARIABLE_productName:identifier___InteractorOutputState {
    case empty
    case error(NSError)
    case populate(___VARIABLE_productName:identifier___ModelProtocol)
}

//MARK: Model -
protocol ___VARIABLE_productName:identifier___ModelProtocol: Codable {

}

//MARK: Router -
protocol ___VARIABLE_productName:identifier___WireframeProtocol: AnyObject {
    func route(_ to: String)
}

//MARK: Presenter -
protocol ___VARIABLE_productName:identifier___PresenterProtocol: AnyObject {
    var inputState: ___VARIABLE_productName:identifier___PresenterState? { get set }
    func route(_ to: String)
}

//MARK: Interactor -
protocol ___VARIABLE_productName:identifier___InteractorOutputProtocol: AnyObject {
    var outputState: ___VARIABLE_productName:identifier___InteractorOutputState? { get set }
}

protocol ___VARIABLE_productName:identifier___InteractorInputProtocol: AnyObject {
    var presenter: ___VARIABLE_productName:identifier___InteractorOutputProtocol?  { get set }
    func fetch()
}

//MARK: View -
protocol ___VARIABLE_productName:identifier___ViewProtocol: AnyObject {
    var presenter: ___VARIABLE_productName:identifier___PresenterProtocol?  { get set }
    var viewState: ___VARIABLE_productName:identifier___ViewState { get set}
}
