//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//
//  Template generated by Sawan Kumar
//

import UIKit

class ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___InteractorInputProtocol {

    weak var presenter: ___VARIABLE_productName:identifier___InteractorOutputProtocol?
    
    func fetch() {
        self.presenter?.outputState = .populate(___VARIABLE_productName:identifier___Model())
    }
}
