//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//
//  Template generated by Sawan Kumar
//

import Foundation


//MARK: View State -
enum ___VARIABLE_productName:identifier___ViewState {
    case initial
    case startLoader
    case stopLoader
    case empty
    case error(NSError)
    case populate(___VARIABLE_productName:identifier___ModelProtocol)
}

//MARK: ViewModel Input State -
enum ___VARIABLE_productName:identifier___ViewModelState {
    case fetch
}

//MARK: ViewModel Output State -
enum ___VARIABLE_productName:identifier___ViewModelOutputState {
    case empty
    case error(NSError)
    case populate(___VARIABLE_productName:identifier___ModelProtocol)
}

//MARK: Model -
protocol ___VARIABLE_productName:identifier___ModelProtocol: Codable {

}

//MARK: ViewModel -
protocol ___VARIABLE_productName:identifier___ViewModelProtocol: AnyObject {
    var inputState: ___VARIABLE_productName:identifier___ViewModelState? { get set }
    func route(_ to: String)
}

//MARK: View -
protocol ___VARIABLE_productName:identifier___ViewProtocol: AnyObject {
    var viewState: ___VARIABLE_productName:identifier___ViewState { get set}
}
