//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//
//  Template generated by Sawan Kumar
//

import Foundation

struct ___VARIABLE_productName:identifier___Model: ___VARIABLE_productName:identifier___ModelProtocol {

    
}
