//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//
//  Template generated by Sawan Kumar
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController {


    override func loadView() {
        super.loadView()
        setupUI()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.fetch()
    }
    
    private func setupUI() {
        self.view.addSubview(containerView)
        containerView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor).isActive = true
        containerView.topAnchor.constraint(equalTo: self.view.topAnchor).isActive = true
        containerView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor).isActive = true
        containerView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor).isActive = true
    }

    private lazy var containerView:___VARIABLE_productName:identifier___View = {
       let instance = ___VARIABLE_productName:identifier___View()
        instance.translatesAutoresizingMaskIntoConstraints = false
        instance.backgroundColor = .white
        return instance
    }()

    func fetch() {
        
    }
}
